alert("VAMOS SOMAR DOIS NUMEROS")
var numberOne = prompt("Digite o primeiro numero")
var numberTwo = prompt("Digite o segundo numero")
let result= Number(numberOne) + Number(numberTwo)
alert("Resultado final:" + result)